site_name: DevilLint Docs
site_url: https://example.com
theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy

nav:
  - ğŸ  InÃ­cio: index.md
  - ğŸ“¦ Modelos:
      - ğŸ¬ Filme (Movie): models/movie.md
      - ğŸ­ Atores (Actor): models/actor.md
      - ğŸ§© Categorias (Category): models/category.md
  - âš™ï¸ ConfiguraÃ§Ãµes:
      - base.py: settings/base.md
      - dev.py: settings/dev.md
      - prod.py: settings/prod.md
  - ğŸš€ Deploy: deploy.md
  - ğŸ§ª Testes: tests.md
  - ğŸ”’ SeguranÃ§a: security.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite